### ISSUE TITLE
msf staged payload - stage is "eaten"

### ISSUE THREAD

**Issue by hawaii67** [D1rkMtr/IORI_Loader#2]
Using a msf staged payload, the stager connects fine, but the stage is eaten up somehow (not executed) - but not by the AV/EDR since there is no on the victim box.

![grafik](https://user-images.githubusercontent.com/13915596/201466699-19045da3-efa2-4861-9d97-1395916188f2.png)

UPDATE:

The binary is crashing before or while the stage is received.

**Comment by hawaii67** [comment]
UPDATE 2 : I fixed it!

**Comment by D1rkMtr** [comment]
Cool !! HOW ? , i need the answer , same , i struggle with it !!

**Comment by hawaii67** [comment]
Well, the program exits before it can receive the stage, so I inserted an endless loop at the end, before the last return, to keep the program running:
`for (;;) {}`

Moreover, to make it stealth, I converted the app from console app to windows app in VS so no windows pops up  :-)

**Comment by D1rkMtr** [comment]
Nice , tnx buddy
